//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGen.Pagination.Data.HelperClasses
{
	/// <summary>Field Creation Class for entity CustomerEntity</summary>
	public partial class CustomerFields
	{
		/// <summary>Creates a new CustomerEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerFieldIndex.Id); }}
		/// <summary>Creates a new CustomerEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerFieldIndex.IsActive); }}
		/// <summary>Creates a new CustomerEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerFieldIndex.Name); }}
		/// <summary>Creates a new CustomerEntity.TableNumber field instance</summary>
		public static EntityField2 TableNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomerFieldIndex.TableNumber); }}
	}

	/// <summary>Field Creation Class for entity OrderEntity</summary>
	public partial class OrderFields
	{
		/// <summary>Creates a new OrderEntity.CustomerId field instance</summary>
		public static EntityField2 CustomerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.CustomerId); }}
		/// <summary>Creates a new OrderEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Id); }}
		/// <summary>Creates a new OrderEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.IsActive); }}
		/// <summary>Creates a new OrderEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Name); }}
		/// <summary>Creates a new OrderEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Price); }}
	}

	/// <summary>Field Creation Class for entity ReceiptEntity</summary>
	public partial class ReceiptFields
	{
		/// <summary>Creates a new ReceiptEntity.CustomerId field instance</summary>
		public static EntityField2 CustomerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReceiptFieldIndex.CustomerId); }}
		/// <summary>Creates a new ReceiptEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReceiptFieldIndex.Id); }}
		/// <summary>Creates a new ReceiptEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReceiptFieldIndex.IsActive); }}
		/// <summary>Creates a new ReceiptEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReceiptFieldIndex.OrderId); }}
	}
	

}