//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using LLBLGen.Pagination.Data.FactoryClasses;
using LLBLGen.Pagination.Data.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGen.Pagination.Data.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCustomerEntityInfo();
			InitOrderEntityInfo();
			InitReceiptEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CustomerEntity's info objects</summary>
		private void InitCustomerEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomerFieldIndex), "CustomerEntity");
			this.AddElementFieldInfo("CustomerEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)CustomerFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CustomerEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)CustomerFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("CustomerEntity", "Name", typeof(System.String), false, false, false, false,  (int)CustomerFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("CustomerEntity", "TableNumber", typeof(System.Int32), false, false, false, false,  (int)CustomerFieldIndex.TableNumber, 0, 0, 10);
		}

		/// <summary>Inits OrderEntity's info objects</summary>
		private void InitOrderEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderFieldIndex), "OrderEntity");
			this.AddElementFieldInfo("OrderEntity", "CustomerId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)OrderFieldIndex.CustomerId, 0, 0, 10);
			this.AddElementFieldInfo("OrderEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)OrderFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("OrderEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)OrderFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Name", typeof(System.String), false, false, false, false,  (int)OrderFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Price", typeof(System.Int32), false, false, false, false,  (int)OrderFieldIndex.Price, 0, 0, 10);
		}

		/// <summary>Inits ReceiptEntity's info objects</summary>
		private void InitReceiptEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ReceiptFieldIndex), "ReceiptEntity");
			this.AddElementFieldInfo("ReceiptEntity", "CustomerId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)ReceiptFieldIndex.CustomerId, 0, 0, 10);
			this.AddElementFieldInfo("ReceiptEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)ReceiptFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("ReceiptEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)ReceiptFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("ReceiptEntity", "OrderId", typeof(System.Int32), false, false, false, false,  (int)ReceiptFieldIndex.OrderId, 0, 0, 10);
		}
	}
}