//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using LLBLGen.Pagination.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGen.Pagination.Crud.Persistence
{
	///<summary>class to define custom where/orderby clauses to be used in the linq / query spec query projection</summary>
	public partial class CustomerViewProjectionParams
	{
		///<summary>class to define custom where/orderby clauses to be used in the linq / query spec query projection</summary>
		public partial class C_OrdersProjectionParams_Clauses
		{
			/// <summary>QuerySpec specific. Appends a new OrderBy clause for the Orders embedded set.</summary>
			/// <param name="clauseToAdd">the clause to add</param>
			public void AppendQSOrderBy(ISortClause clauseToAdd) => this.QSOrderByClauses.Add(clauseToAdd);
			/// <summary>Linq specific. Appends a new OrderBy clause for the Orders embedded set.</summary>
			/// <param name="orderByClause">The order by clause to use</param>
			/// <param name="descending">if true, the order by will be descending, otherwise ascending (default)</param>
			/// <typeparam name="TField">The type of the field to sort by</typeparam>
			public void AppendLinqOrderBy<TField>(System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.OrderEntity, TField>> orderByClause, bool descending = false) => this.LinqOrderByClauses.Add(new SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>((System.Linq.Expressions.Expression)orderByClause, descending));
			internal List<SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>> LinqOrderByClauses { get; } = new List<SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>>();
			internal List<ISortClause> QSOrderByClauses { get; set; } = new List<ISortClause>();
			/// <summary>Linq specific. Custom where clause to be used for when the Orders embedded set is fetched</summary>
			public System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.OrderEntity, bool>> LinqWhereClause { get; set; }
			/// <summary>QuerySpec specific. Custom where clause to be used for when the Orders embedded set is fetched</summary>
			public IPredicate QSWhereClause { get; set; }
		}

		///<summary>class to define custom where/orderby clauses to be used in the linq / query spec query projection</summary>
		public partial class C_ReceiptsProjectionParams_Clauses
		{
			/// <summary>QuerySpec specific. Appends a new OrderBy clause for the Receipts embedded set.</summary>
			/// <param name="clauseToAdd">the clause to add</param>
			public void AppendQSOrderBy(ISortClause clauseToAdd) => this.QSOrderByClauses.Add(clauseToAdd);
			/// <summary>Linq specific. Appends a new OrderBy clause for the Receipts embedded set.</summary>
			/// <param name="orderByClause">The order by clause to use</param>
			/// <param name="descending">if true, the order by will be descending, otherwise ascending (default)</param>
			/// <typeparam name="TField">The type of the field to sort by</typeparam>
			public void AppendLinqOrderBy<TField>(System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, TField>> orderByClause, bool descending = false) => this.LinqOrderByClauses.Add(new SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>((System.Linq.Expressions.Expression)orderByClause, descending));
			internal List<SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>> LinqOrderByClauses { get; } = new List<SD.LLBLGen.Pro.ORMSupportClasses.ValuePair<System.Linq.Expressions.Expression, bool>>();
			internal List<ISortClause> QSOrderByClauses { get; set; } = new List<ISortClause>();
			/// <summary>Linq specific. Custom where clause to be used for when the Receipts embedded set is fetched</summary>
			public System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, bool>> LinqWhereClause { get; set; }
			/// <summary>QuerySpec specific. Custom where clause to be used for when the Receipts embedded set is fetched</summary>
			public IPredicate QSWhereClause { get; set; }
		}

		/// <summary>Projection parameters to configure where / orderby clauses for the nested member 'Orders'</summary>
		public C_OrdersProjectionParams_Clauses OrdersProjectionParams { get; } = new C_OrdersProjectionParams_Clauses();
		/// <summary>Projection parameters to configure where / orderby clauses for the nested member 'Receipts'</summary>
		public C_ReceiptsProjectionParams_Clauses ReceiptsProjectionParams { get; } = new C_ReceiptsProjectionParams_Clauses();
	}

	/// <summary>Static class for (extension) methods for fetching and projecting instances of LLBLGen.Pagination.Crud.DtoClasses.CustomerView from the entity model.</summary>
	public static partial class CustomerViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerView> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToCustomerView(System.Linq.IQueryable{LLBLGen.Pagination.Data.EntityClasses.CustomerEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToCustomerView(ref System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToCustomerView(EntityQuery{LLBLGen.Pagination.Data.EntityClasses.CustomerEntity}, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToCustomerView(EntityQuery{LLBLGen.Pagination.Data.EntityClasses.CustomerEntity}, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToCustomerViewQs(ref System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static CustomerViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerView which instances are projected from the results of the specified baseQuery, which returns LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve LLBLGen.Pagination.Crud.DtoClasses.CustomerView instances</returns>
		public static IQueryable<LLBLGen.Pagination.Crud.DtoClasses.CustomerView> ProjectToCustomerView(this IQueryable<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity> baseQuery) => ProjectToCustomerView(baseQuery, null);
		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerView which instances are projected from the results of the specified baseQuery, which returns LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="projectionParams">The optional projection parameters with optional where/orderby clauses for nested sets in the projection</param>
		/// <returns>IQueryable to retrieve LLBLGen.Pagination.Crud.DtoClasses.CustomerView instances</returns>
		public static IQueryable<LLBLGen.Pagination.Crud.DtoClasses.CustomerView> ProjectToCustomerView(this IQueryable<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity> baseQuery, CustomerViewProjectionParams projectionParams)
		{
			if(projectionParams == null)
			{
				return baseQuery.Select(_projectorExpression);
			}
			return baseQuery.Select(CreateProjectionFunc(projectionParams));
		}

		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve LLBLGen.Pagination.Crud.DtoClasses.CustomerView instances</returns>
		public static DynamicQuery<LLBLGen.Pagination.Crud.DtoClasses.CustomerView> ProjectToCustomerView(this EntityQuery<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity> baseQuery, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory qf) => ProjectToCustomerView(baseQuery, qf, null);
		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <param name="projectionParams">The optional projection parameters with optional where/orderby clauses for nested sets in the projection</param>
		/// <returns>DynamicQuery to retrieve LLBLGen.Pagination.Crud.DtoClasses.CustomerView instances</returns>
		public static DynamicQuery<LLBLGen.Pagination.Crud.DtoClasses.CustomerView> ProjectToCustomerView(this EntityQuery<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity> baseQuery, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory qf, CustomerViewProjectionParams projectionParams=null)
		{
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToCustomerViewQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new LLBLGen.Pagination.Crud.DtoClasses.CustomerView()
				{
					Id = CustomerFields.Id.Source("__BQ").ToValue<System.Int32>(),
					IsActive = CustomerFields.IsActive.Source("__BQ").ToValue<System.Boolean>(),
					Name = CustomerFields.Name.Source("__BQ").ToValue<System.String>(),
					Orders = (List<LLBLGen.Pagination.Crud.DtoClasses.CustomerViewTypes.Order>)qf.Order.TargetAs("__L1_0")
						.CorrelatedOver(CustomerFields.Id.Source("__BQ").Equal(OrderFields.CustomerId.Source("__L1_0")))
						.Where(projectionParams==null ? null : GeneralUtils.SetAliasOnPredicate(projectionParams.OrdersProjectionParams.QSWhereClause, "__L1_0"))
						.OrderBy(projectionParams==null ? null : GeneralUtils.SetAliasOnSortClauses(projectionParams.OrdersProjectionParams.QSOrderByClauses, "__L1_0"))
						.Select(() => new LLBLGen.Pagination.Crud.DtoClasses.CustomerViewTypes.Order()
						{
							CustomerId = OrderFields.CustomerId.Source("__L1_0").ToValue<Nullable<System.Int32>>(),
							Id = OrderFields.Id.Source("__L1_0").ToValue<System.Int32>(),
							IsActive = OrderFields.IsActive.Source("__L1_0").ToValue<System.Boolean>(),
							Name = OrderFields.Name.Source("__L1_0").ToValue<System.String>(),
							Price = OrderFields.Price.Source("__L1_0").ToValue<System.Int32>(),
						}).ToResultset(),
					Receipts = (List<LLBLGen.Pagination.Crud.DtoClasses.CustomerViewTypes.Receipt>)qf.Receipt.TargetAs("__L1_0")
						.CorrelatedOver(CustomerFields.Id.Source("__BQ").Equal(ReceiptFields.CustomerId.Source("__L1_0")))
						.Where(projectionParams==null ? null : GeneralUtils.SetAliasOnPredicate(projectionParams.ReceiptsProjectionParams.QSWhereClause, "__L1_0"))
						.OrderBy(projectionParams==null ? null : GeneralUtils.SetAliasOnSortClauses(projectionParams.ReceiptsProjectionParams.QSOrderByClauses, "__L1_0"))
						.Select(() => new LLBLGen.Pagination.Crud.DtoClasses.CustomerViewTypes.Receipt()
						{
							CustomerId = ReceiptFields.CustomerId.Source("__L1_0").ToValue<Nullable<System.Int32>>(),
							Id = ReceiptFields.Id.Source("__L1_0").ToValue<System.Int32>(),
							IsActive = ReceiptFields.IsActive.Source("__L1_0").ToValue<System.Boolean>(),
							OrderId = ReceiptFields.OrderId.Source("__L1_0").ToValue<System.Int32>(),
						}).ToResultset(),
					TableNumber = CustomerFields.TableNumber.Source("__BQ").ToValue<System.Int32>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_CustomerView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerView which instances are projected from the LLBLGen.Pagination.Data.EntityClasses.CustomerEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instance created from the specified entity instance</returns>
		public static LLBLGen.Pagination.Crud.DtoClasses.CustomerView ProjectToCustomerView(this LLBLGen.Pagination.Data.EntityClasses.CustomerEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> CreateProjectionFunc(CustomerViewProjectionParams projectionParams=null)
		{
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> mainProjection = p__0 => new LLBLGen.Pagination.Crud.DtoClasses.CustomerView()
			{
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				Name = p__0.Name,
				Orders = p__0.Orders.AsQueryable().OptionalWhere(projectionParams==null ? null : projectionParams.OrdersProjectionParams.LinqWhereClause).OptionalOrderBy(projectionParams==null ? null : projectionParams.OrdersProjectionParams.LinqOrderByClauses).Select(p__1 => new LLBLGen.Pagination.Crud.DtoClasses.CustomerViewTypes.Order()
				{
					CustomerId = p__1.CustomerId,
					Id = p__1.Id,
					IsActive = p__1.IsActive,
					Name = p__1.Name,
					Price = p__1.Price,
				}).ToList(),
				Receipts = p__0.Receipts.AsQueryable().OptionalWhere(projectionParams==null ? null : projectionParams.ReceiptsProjectionParams.LinqWhereClause).OptionalOrderBy(projectionParams==null ? null : projectionParams.ReceiptsProjectionParams.LinqOrderByClauses).Select(p__1 => new LLBLGen.Pagination.Crud.DtoClasses.CustomerViewTypes.Receipt()
				{
					CustomerId = p__1.CustomerId,
					Id = p__1.Id,
					IsActive = p__1.IsActive,
					OrderId = p__1.OrderId,
				}).ToList(),
				TableNumber = p__0.TableNumber,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_CustomerView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToCustomerView(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


