//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.13.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using LLBLGen.Pagination.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGen.Pagination.Crud.Persistence
{

	/// <summary>Static class for (extension) methods for fetching and projecting instances of LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView from the entity model.</summary>
	public static partial class CustomerSimpleViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToCustomerSimpleView(System.Linq.IQueryable{LLBLGen.Pagination.Data.EntityClasses.CustomerEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToCustomerSimpleView(ref System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToCustomerSimpleView(EntityQuery{LLBLGen.Pagination.Data.EntityClasses.CustomerEntity}, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToCustomerSimpleView(EntityQuery{LLBLGen.Pagination.Data.EntityClasses.CustomerEntity}, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToCustomerSimpleViewQs(ref System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static CustomerSimpleViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView which instances are projected from the results of the specified baseQuery, which returns LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView instances</returns>
		public static IQueryable<LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView> ProjectToCustomerSimpleView(this IQueryable<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView which instances are projected from the results of the specified baseQuery using QuerySpec, which returns LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView instances</returns>
		public static DynamicQuery<LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView> ProjectToCustomerSimpleView(this EntityQuery<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity> baseQuery, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToCustomerSimpleViewQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView()
				{
					Id = CustomerFields.Id.Source("__BQ").ToValue<System.Int32>(),
					IsActive = CustomerFields.IsActive.Source("__BQ").ToValue<System.Boolean>(),
					Name = CustomerFields.Name.Source("__BQ").ToValue<System.String>(),
					TableNumber = CustomerFields.TableNumber.Source("__BQ").ToValue<System.Int32>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_CustomerSimpleView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView which instances are projected from the LLBLGen.Pagination.Data.EntityClasses.CustomerEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>LLBLGen.Pagination.Data.EntityClasses.CustomerEntity instance created from the specified entity instance</returns>
		public static LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView ProjectToCustomerSimpleView(this LLBLGen.Pagination.Data.EntityClasses.CustomerEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> mainProjection = p__0 => new LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView()
			{
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				Name = p__0.Name,
				TableNumber = p__0.TableNumber,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_CustomerSimpleView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.CustomerEntity, LLBLGen.Pagination.Crud.DtoClasses.CustomerSimpleView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToCustomerSimpleView(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


