//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.13.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using LLBLGen.Pagination.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.LinqSupportClasses.DTOProjectionHelpers;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGen.Pagination.Crud.Persistence
{

	/// <summary>Static class for (extension) methods for fetching and projecting instances of LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer from the entity model.</summary>
	public static partial class ReceiptCustomerPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToReceiptCustomer(System.Linq.IQueryable{LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToReceiptCustomer(ref System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToReceiptCustomer(EntityQuery{LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity}, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToReceiptCustomer(EntityQuery{LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity}, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToReceiptCustomerQs(ref System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static ReceiptCustomerPersistence() { }
	
		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer which instances are projected from the results of the specified baseQuery, which returns LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer instances</returns>
		public static IQueryable<LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer> ProjectToReceiptCustomer(this IQueryable<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer which instances are projected from the results of the specified baseQuery using QuerySpec, which returns LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer instances</returns>
		public static DynamicQuery<LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer> ProjectToReceiptCustomer(this EntityQuery<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity> baseQuery, LLBLGen.Pagination.Data.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> projectionAdjustments = null;
			GetAdjustmentsForProjectToReceiptCustomerQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ")
					.LeftJoin(qf.Customer.As("__L0_0")).On(ReceiptFields.CustomerId.Source("__BQ").Equal(CustomerFields.Id.Source("__L0_0"))))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer()
				{
					Customer = new LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomerTypes.Customer()
						{
							Id = CustomerFields.Id.Source("__L0_0").ToValue<System.Int32>(),
							IsActive = CustomerFields.IsActive.Source("__L0_0").ToValue<System.Boolean>(),
							Name = CustomerFields.Name.Source("__L0_0").ToValue<System.String>(),
							TableNumber = CustomerFields.TableNumber.Source("__L0_0").ToValue<System.Int32>(),
						},
					CustomerId = ReceiptFields.CustomerId.Source("__BQ").ToValue<Nullable<System.Int32>>(),
					Id = ReceiptFields.Id.As("Id1").Source("__BQ").ToValue<System.Int32>(),
					IsActive = ReceiptFields.IsActive.As("IsActive1").Source("__BQ").ToValue<System.Boolean>(),
					OrderId = ReceiptFields.OrderId.Source("__BQ").ToValue<System.Int32>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_ReceiptCustomer 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer which instances are projected from the LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity instance created from the specified entity instance</returns>
		public static LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer ProjectToReceiptCustomer(this LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity entity)
		{
			return _compiledProjector(entity);
		}

		private static System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> mainProjection = p__0 => new LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer()
			{
				Customer = new LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomerTypes.Customer()
				{
					Id = p__0.Customer.Id,
					IsActive = p__0.Customer.IsActive,
					Name = p__0.Customer.Name,
					TableNumber = p__0.Customer.TableNumber,
				},
				CustomerId = p__0.CustomerId,
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				OrderId = p__0.OrderId,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_ReceiptCustomer 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<LLBLGen.Pagination.Data.EntityClasses.ReceiptEntity, LLBLGen.Pagination.Crud.DtoClasses.ReceiptCustomer>> projectionAdjustments = null;
			GetAdjustmentsForProjectToReceiptCustomer(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


