//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using LLBLGen.Pagination.Data.HelperClasses;
using LLBLGen.Pagination.Data.FactoryClasses;
using LLBLGen.Pagination.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace LLBLGen.Pagination.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Receipt'.<br/><br/></summary>
	[Serializable]
	public partial class ReceiptEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private CustomerEntity _customer;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ReceiptEntityStaticMetaData _staticMetaData = new ReceiptEntityStaticMetaData();
		private static ReceiptRelations _relationsFactory = new ReceiptRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Customer</summary>
			public static readonly string Customer = "Customer";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReceiptEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReceiptEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReceiptEntity", InheritanceHierarchyType.None, false, (int)LLBLGen.Pagination.Data.EntityType.ReceiptEntity, typeof(ReceiptEntity), typeof(ReceiptEntityFactory), false);
				AddNavigatorMetaData<ReceiptEntity, CustomerEntity>("Customer", "Receipts", (a, b) => a._customer = b, a => a._customer, (a, b) => a.Customer = b, LLBLGen.Pagination.Data.RelationClasses.StaticReceiptRelations.CustomerEntityUsingCustomerIdStatic, ()=>new ReceiptRelations().CustomerEntityUsingCustomerId, null, new int[] { (int)ReceiptFieldIndex.CustomerId }, null, true, (int)LLBLGen.Pagination.Data.EntityType.CustomerEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReceiptEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReceiptEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReceiptEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReceiptEntity</param>
		public ReceiptEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Receipt which data should be fetched into this Receipt object</param>
		public ReceiptEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Receipt which data should be fetched into this Receipt object</param>
		/// <param name="validator">The custom validator object for this ReceiptEntity</param>
		public ReceiptEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReceiptEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Customer' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCustomer() { return CreateRelationInfoForNavigator("Customer"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReceiptEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReceiptRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Customer' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCustomer { get { return _staticMetaData.GetPrefetchPathElement("Customer", CommonEntityBase.CreateEntityCollection<CustomerEntity>()); } }

		/// <summary>The CustomerId property of the Entity Receipt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Receipt"."CustomerId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ReceiptFieldIndex.CustomerId, false); }
			set { SetValue((int)ReceiptFieldIndex.CustomerId, value); }
		}

		/// <summary>The Id property of the Entity Receipt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Receipt"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ReceiptFieldIndex.Id, true); }
			set { SetValue((int)ReceiptFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Receipt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Receipt"."IsActive".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)ReceiptFieldIndex.IsActive, true); }
			set { SetValue((int)ReceiptFieldIndex.IsActive, value); }
		}

		/// <summary>The OrderId property of the Entity Receipt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Receipt"."OrderId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 OrderId
		{
			get { return (System.Int32)GetValue((int)ReceiptFieldIndex.OrderId, true); }
			set { SetValue((int)ReceiptFieldIndex.OrderId, value); }
		}

		/// <summary>Gets / sets related entity of type 'CustomerEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CustomerEntity Customer
		{
			get { return _customer; }
			set { SetSingleRelatedEntityNavigator(value, "Customer"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace LLBLGen.Pagination.Data
{
	public enum ReceiptFieldIndex
	{
		///<summary>CustomerId. </summary>
		CustomerId,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>OrderId. </summary>
		OrderId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace LLBLGen.Pagination.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Receipt. </summary>
	public partial class ReceiptRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReceiptEntity and CustomerEntity over the m:1 relation they have, using the relation between the fields: Receipt.CustomerId - Customer.Id</summary>
		public virtual IEntityRelation CustomerEntityUsingCustomerId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Customer", false, new[] { CustomerFields.Id, ReceiptFields.CustomerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReceiptRelations
	{
		internal static readonly IEntityRelation CustomerEntityUsingCustomerIdStatic = new ReceiptRelations().CustomerEntityUsingCustomerId;

		/// <summary>CTor</summary>
		static StaticReceiptRelations() { }
	}
}
