//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace LLBLGen.Pagination.Crud.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Customer'.</summary>
	[Serializable]
	[DataContract]
	public partial class CustomerReceipt
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Customer.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Customer.IsActive'</summary>
		[DataMember]
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Customer.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Receipts field. </summary>
		[DataMember]
		public List<CustomerReceiptTypes.Receipt> Receipts { get; set; }
		/// <summary>Gets or sets the TableNumber field. Derived from Entity Model Field 'Customer.TableNumber'</summary>
		[DataMember]
		public System.Int32 TableNumber { get; set; }
	}

	namespace CustomerReceiptTypes
	{
		/// <summary> DTO class which is derived from the entity 'Receipt (Receipts)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Receipt
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Receipt.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
		}
	}

}




