//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace LLBLGen.Pagination.Crud.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Receipt'.</summary>
	[Serializable]
	[DataContract]
	public partial class ReceiptCustomer
	{
		/// <summary>Gets or sets the Customer field. </summary>
		[DataMember]
		public ReceiptCustomerTypes.Customer Customer { get; set; }
		/// <summary>Gets or sets the CustomerId field. Derived from Entity Model Field 'Receipt.CustomerId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> CustomerId { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Receipt.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Receipt.IsActive'</summary>
		[DataMember]
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the OrderId field. Derived from Entity Model Field 'Receipt.OrderId'</summary>
		[DataMember]
		public System.Int32 OrderId { get; set; }
	}

	namespace ReceiptCustomerTypes
	{
		/// <summary> DTO class which is derived from the entity 'Customer (Customer)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Customer
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Customer.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Customer.IsActive'</summary>
			[DataMember]
			public System.Boolean IsActive { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Customer.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
			/// <summary>Gets or sets the TableNumber field. Derived from Entity Model Field 'Customer.TableNumber'</summary>
			[DataMember]
			public System.Int32 TableNumber { get; set; }
		}
	}

}




